
import React from "react";
import "./home.css";

import { Link } from "react-router-dom";

import logo1 from '../../images/logo_1.jpg';
import logo2 from '../../images/logo_2.jpg';
import logo3 from '../../images/logo_3.jpg';
import logo4 from '../../images/logo_4.jpg';


function Home() {
  return (
    <div className="home">
      <section className="otmt_section">
        <div className="otmt">
        <h1>Office of Technology Management and Transfer</h1>
        <br />
          <div className="title_decoration"> hello</div>
        <br />
        <p>
          At IIIT Delhi, we are driven by innovation, collaboration, and the
          pursuit of a brighter future. Our multifaceted Office of Technology
          Management and Transfer (OTMT) is at the forefront of fostering
          positive change, advancing technology, and ensuring innovation has a
          long lasting impact.
        </p>
        <br />
        <p>
          Innovation is at the heart of what we do. The division is dedicated to
          the advancement, commercialization, and licensing of technology and
          intellectual assets generated by our talented faculty, researchers,
          students, and collaborators and also supports students, faculty and
          researchers and Entrepreneurs who need our expertise.
        </p>
      
        </div>
        </section>
      <section className="what-we-do">
        <div id="what_we_do">
          <h2>What we do</h2>
          <div
            className="title_decoration"
            style={{ height: "0.25rem", width: "35vh", "margin-right": "7vh" }}
          >
            {" "}
            hello
          </div>
          <div className="services">
            <div className="service-item">
            Creating Awareness and Sensitization{" "}
              <p>
              We raise awareness about technology and innovation, ensuring that promising ideas don't go unnoticed.
              </p>{" "}
            </div>
            <div className="service-item">
              Find the best ways to sell Innovations{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Finding and getting new Tech{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Teaming up for special Research{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Supporting Intellectual Properties{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Easing the handover of Technology{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Linking Up Innovators{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
            <div className="service-item">
              Linking up Innovators{" "}
              <p>
                We help figure out the smartest ways to market new inventions so
                they stand out and reach the right people.
              </p>
            </div>
          </div>
        </div>
      </section>


      <section className="technology-highlights">
        <div id='technology_highlights'>
          <h2>Technology Highlights</h2>
          <div className="title_decoration" style={{"height" : "0.25rem", "width" : "25vw"}}> hello</div>
          <div className="highlights">
            <div className="highlight-item">
              <img src={logo1} alt="Seek and Suspect" />
              <p>Seek and Suspect</p>
              <p className='text'> The novel aspect of this project lies in an innovative and fully automated technology for facial image retrieval in criminal investigations.</p>
            </div>
            <div className="highlight-item">
              <img src={logo2} alt="Cloud Labs" />
              <p>Cloud Labs</p>
            </div>
            <div className="highlight-item">
              <img src={logo3} alt="TATDC" />
              <p>TATDC</p>
            </div>
            <div className="highlight-item">
              <img src={logo4} alt="FOODLE" />
              <p>FOODLE</p>
            </div>
          </div>
          <div className="background_block"> hello  </div>
        </div>
      </section>

</div>
  );
}
      

export default Home;
