import React from 'react'
import "./home.css";
import { Link } from "react-router-dom";



function Home() {
  return (
    <div className="home">
      <section className="otmt">
        <h1>Office of Technology Management and Transfer</h1>
        <p>
          At IIIT Delhi, we are driven by innovation, collaboration, and the pursuit of a brighter future. 
          Our multifaceted Office of Technology Management and Transfer (OTMT) is at the forefront of fostering 
          positive change, advancing technology, and ensuring innovation has a long lasting impact.
        </p>
        <p>
          Innovation is at the heart of what we do. The division is dedicated to the advancement, commercialization, 
          and licensing of technology and intellectual assets generated by our talented faculty, researchers, students, 
          and collaborators and also supports students, faculty and researchers and Entrepreneurs who need our expertise.
        </p>
      </section>
      <section className="what-we-do">
        <h2>What we do</h2>
        <div className="services">
          <div className="service-item">Accessing Commercial Potential</div>
          <div className="service-item">Find the best ways to sell Innovations</div>
          <div className="service-item">Finding and getting new Tech</div>
          <div className="service-item">Teaming up for special Research</div>
          <div className="service-item">Supporting Intellectual Properties</div>
          <div className="service-item">Easing the handover of Technology</div>
          <div className="service-item">Linking Up Innovators</div>
          <div className="service-item">Creating Awareness and Sensitization</div>
        </div>
      </section>
      <section className="technology-highlights">
        <h2>Technology Highlights</h2>
        <div className="highlights">
          <div className="highlight-item">
            <img src="seek-and-suspect.png" alt="Seek and Suspect" />
            <p>Seek and Suspect</p>
          </div>
          <div className="highlight-item">
            <img src="cloud-labs.png" alt="Cloud Labs" />
            <p>Cloud Labs</p>
          </div>
          <div className="highlight-item">
            <img src="tatdc.png" alt="TATDC" />
            <p>TATDC</p>
          </div>
          <div className="highlight-item">
            <img src="foodle.png" alt="FOODLE" />
            <p>FOODLE</p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Home;

